spring:
    application:
        name: demo
    ai:
        chat:
            client: 
                enabled: false # Spring AI auto-configures a single ChatClient.Builder bean by default.
                               # Disabling ChatClient.Builder auto-configuration allows to manually
                               # configure multiple bean and inject them where needed.
        ollama:
            base-url: http://172.19.0.2:11434
            init:
                pull-model-strategy: when_missing
                timeout: 15m
                max-retries: 3 
            chat:
              options:
                model: VitoF/llama-3.1-8b-italian
                temperature: 0.2
                top-k: 40
                top-p: 0.9
                repeat-penalty: 1.1 
                presence-penalty: 1.0
        openai:
            api-key: ${GOOGLE_AI_API_KEY}
            base-url: https://generativelanguage.googleapis.com/v1beta/openai
            chat:
                completions-path: /chat/completions
                options:
                    model: gemini-2.0-flash-lite
                    temperature: 2.0