spring:
    ai:
        chat:
            ...
            memory:
                repository:
                    jdbc:
                        initialize-schema: always # always, never, embedded (default)
                        schema: classpath:/schema/schema-h2.sql
    ...
    datasource:
        url: jdbc:h2:file:./db/chatmemory
        driver-class-name: org.h2.Driver
        username: user
        password: pwd
    h2:
        console:
            enabled: true
...