spring:
    application:
        name: demo
    ai:
        openai:
            api-key: pippoplutopaperino
            base-url: http://localhost:12434/engines
            chat:
                options:
                    model: ai/gemma3